// CARS
export const GET_CARS_START = "GET_CARS_START";
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_FAIL = "GET_CARS_FAIL";

//AUTHENTICATION
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT"